# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 05:26
from __future__ import unicode_literals

import os
import ujson

from django.conf import settings
from django.db import migrations, models

# TODO: Replace this with a hardcoding of a permanent version of this data set.
path_to_name_to_codepoint = os.path.join(settings.STATIC_ROOT, "generated", "emoji", "name_to_codepoint.json")
name_to_codepoint = ujson.load(open(path_to_name_to_codepoint))

def copy_emoji_name_to_codepoint(apps, schema_editor):
    # type: (StateApps, DatabaseSchemaEditor) -> None
    Reaction = apps.get_model('zerver', 'Reaction')
    for reaction in Reaction.objects.all():
        reaction.codepoint = name_to_codepoint.get(reaction.emoji_name)
        if reaction.codepoint is None:
            # If it's not present in the name_to_codepoint map, it's a realm emoji.
            reaction.is_realm_emoji = True
            reaction.codepoint = reaction.emoji_name
        reaction.save()

class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0078_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='codepoint',
            field=models.TextField(default='unset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reaction',
            name='is_realm_emoji',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(copy_emoji_name_to_codepoint,
                             reverse_code=migrations.RunPython.noop),
    ]
