# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-03 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0241_usermessage_bigint_id_migration_finalize'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wildcard_mention_audible_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wildcard_mention_desktop_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wildcard_mention_email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wildcard_mention_push_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
