# Generated by Django 2.2.10 on 2020-02-19 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0269_gitlab_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_pointer_updater',
        ),
    ]
