# Generated by Django 3.2.6 on 2021-09-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0343_alter_useractivityinterval_index_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="type",
            field=models.PositiveSmallIntegerField(choices=[(1, "Normal")], null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="type",
            field=models.PositiveSmallIntegerField(choices=[(1, "Normal")], null=True),
        ),
    ]
