# Generated by Django 3.2.6 on 2021-09-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0344_add_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedmessage",
            name="type",
            field=models.PositiveSmallIntegerField(choices=[(1, "Normal")], default=1, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.PositiveSmallIntegerField(choices=[(1, "Normal")], default=1, null=True),
        ),
    ]
