# Generated by Django 4.2.7 on 2023-11-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0490_renumber_options_desktop_icon_count_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="push_notifications_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="realm",
            name="push_notifications_enabled_end_date",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
