# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_add_on_delete'),
        ('zilencer', '0015_delete_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteInstallationCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=32)),
                ('subgroup', models.CharField(max_length=16, null=True)),
                ('end_time', models.DateTimeField()),
                ('value', models.BigIntegerField()),
                ('remote_id', models.BigIntegerField(db_index=True)),
                ('anomaly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.Anomaly')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zilencer.RemoteZulipServer')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteRealmCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=32)),
                ('subgroup', models.CharField(max_length=16, null=True)),
                ('end_time', models.DateTimeField()),
                ('value', models.BigIntegerField()),
                ('realm_id', models.BigIntegerField(db_index=True)),
                ('remote_id', models.BigIntegerField(db_index=True)),
                ('anomaly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.Anomaly')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zilencer.RemoteZulipServer')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='remoterealmcount',
            unique_together=set([('server', 'realm_id', 'property', 'subgroup', 'end_time')]),
        ),
        migrations.AlterIndexTogether(
            name='remoterealmcount',
            index_together=set([('property', 'end_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='remoteinstallationcount',
            unique_together=set([('server', 'property', 'subgroup', 'end_time')]),
        ),
    ]
